// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA1nwMx9SNwWV1WW41N5r6ytBXQDMxp-Q',
    appId: '1:197191556022:web:3fd1b95176025630c0bf17',
    messagingSenderId: '197191556022',
    projectId: 'book-donate-firebase',
    authDomain: 'book-donate-firebase.firebaseapp.com',
    storageBucket: 'book-donate-firebase.appspot.com',
    measurementId: 'G-NW9W665MR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbo8knObWy1WD5tKrFSs5womgh34Wh4Zs',
    appId: '1:197191556022:android:0b5a805f32901c61c0bf17',
    messagingSenderId: '197191556022',
    projectId: 'book-donate-firebase',
    storageBucket: 'book-donate-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhYRXpsruWmlOAdg4sTNlny9LWY5LIag',
    appId: '1:197191556022:ios:2ad047e5fc0cd215c0bf17',
    messagingSenderId: '197191556022',
    projectId: 'book-donate-firebase',
    storageBucket: 'book-donate-firebase.appspot.com',
    iosBundleId: 'com.example.flutterTestApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZhYRXpsruWmlOAdg4sTNlny9LWY5LIag',
    appId: '1:197191556022:ios:35aee3d8ed8c3ab5c0bf17',
    messagingSenderId: '197191556022',
    projectId: 'book-donate-firebase',
    storageBucket: 'book-donate-firebase.appspot.com',
    iosBundleId: 'com.example.flutterTestApplication.RunnerTests',
  );
}
